version: "3.7"

networks:
  default:
    name: video_api_network

services:
  mongo:
    image: mongo:4
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=thalesmorato
      - MONGO_INITDB_ROOT_PASSWORD=senha123
  app:
    build: .
    container_name: video_api
    ports:
      - 3333:3333
      - 9229:9229 #Você pode inserir essa porta tbm pra poder usar o debug
    volumes:
      - .:/usr/app
      - /usr/src/app/node_modules
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - MONGODB_DATABASE=movie_db
      - MONGODB_USERNAME=thalesmorato
      - MONGODB_PASSWORD=senha123
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - JWT_KEY=07ed6d3a2a485ede0afd99b17ebbb448
